name: tag
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tag latest release on github
        run: bash .github/tag_release.sh
        env:
          UTIL_SECRET: ${{ secrets.SECRET }}
